### ISSUE TITLE
Incremental build

### ISSUE THREAD

**Issue by TrySound** [showpad/karma-rollup-preprocessor#10]
The last version of rollup introduced incremental build. You can pass previous `bundle` as `cache` option. This will let to improve performance of testing a lot. Also you can track imported files via watcher which could simplify test driven development.
Here's an example https://github.com/rollup/rollup-watch/blob/master/src/index.js

**Comment by TrySound** [comment]
/cc @klaascuvelier
Also would be great if you will write some tests for this project. Because
```js
import helper from './helper';

describe('Helper', () => {
    it('should be defined', () => {
        expect(helper).toBeDefined();
    });
});
```
doesn't seem trusty.

**Comment by jonnyOwnTheWorld** [comment]
Seems like a better plugin is located here: https://www.npmjs.com/package/rollup-plugin-karma
