### ISSUE TITLE
Typeof transform

### ISSUE THREAD

**Issue by derduher** [showpad/karma-rollup-preprocessor#13]
The version of rollup this package is locked to appears to be causing a type of error seen here https://github.com/rollup/rollup-plugin-babel/issues/69

Please update to the latest or merge #12

**Comment by Kflash** [comment]
@derduher use this repo instead https://github.com/Kflash/karma-rollup-plugin

**Comment by derduher** [comment]
@Kflash Worked perfectly thanks!
