### ISSUE TITLE
Better logging of bundling errors

### ISSUE THREAD

**Issue by brianmhunt** [showpad/karma-rollup-preprocessor#4]
I noticed that bundling errors seem to fall silent.

The simplest workaround is to add e.g.

```javascript
log.error("Bundle error:", error)
```

at https://github.com/showpad/karma-rollup-preprocessor/blob/master/lib/index.js#L44

I don't know Karma's internal workings well enough to speculate why `done(error, null)` does not report the error, but I noted the coffee plugin [similarly logs a message](https://github.com/karma-runner/karma-coffee-preprocessor/blob/master/index.js#L32) with

```javascript
      log.error('%s\n  at %s:%d', e.message, file.originalPath, e.location.first_line)
```

Cheers.

**Comment by klaascuvelier** [comment]
Implemented by #5
