### ISSUE TITLE
Sorry in advance

### ISSUE THREAD

**Issue by thepian** [showpad/karma-rollup-preprocessor#6]
Sorry in advance for a poor bug report.

I'm trying out the preprocessor and have it working without plugins, however it seems the rollup doesn't include the imports. I assume the Babel plugin is needed for things to work properly.

So I tried your example of adding 'rollup-plugin-babel', but when I do that the Karma server never takes off. There is no debug output, Karma just finishes.

Do you have any suggestions for how to debug this?

**Comment by thepian** [comment]
Actually I missed a cool part of rollup. Since I didn't refer to the imported source code it was removed ending up in a test without implementation. Once I referenced the source in a test it gets pulled in.

**Comment by klaascuvelier** [comment]
Glad you were able to resolve your own issue :) :+1:

**Comment by jellymann** [comment]
@thepian Hi, I seem to be getting the same issue as you. Karma is finishing with no output, however even if I reference the imported code it still does not work. I suspect it has something to do with the es2015 class syntax, as removing classes allows karma to run.

Here is a small example that reproduces my issue.

```javascript
// test/foo_test.js
import Foo from "../src/foo";

describe("foo", () => {
  it("bar", () => {
    assert.equal(new Foo().bar(), "baz");
  });
});
```

```javascript
// src/foo.js

export default class Foo {
  bar() {
    return "baz";
  }
}
```

```javascript
// karma.conf.js

module.exports = function(config) {
  config.set({
    basePath: "",
    frameworks: ["mocha", "chai"],
    files: [
      "test/**/*_test.js"
    ],
    preprocessors: {
      "test/**/*_test.js": ["rollup"]
    },
    exclude: [],
    rollupPreprocessor: {
      rollup: {
        plugins: [
          require("rollup-plugin-node-resolve")(),
          require("rollup-plugin-commonjs")({
            exclude: ["src/**", "test/**/*.js"]
          }),
          require("rollup-plugin-babel")({
            exclude: "node_modules/**",
            presets: [require("babel-preset-es2015-rollup")],
            babelrc: false
          })
        ]
      },
      bundle: {
        sourceMap: "inline"
      }
    },
    reporters: ["progress"],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ["Chrome"],
    singleRun: true,
    concurrency: Infinity
  });
};
```

**Comment by jlmakes** [comment]
I think this is related to #4. I noticed an invalid configuration was causing the bundle (and Karma) to fail silently. I'm working on better error handling, to fix these silent failures.
